services:
  cdktf:
    build:
      context: .
      dockerfile: docker/cdktf/Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - USER_NAME=${USER_NAME}
        - USER_GROUP=${USER_GROUP}
    volumes:
      - .:/workspace:cached
      - ../cdktf-toolkit:/workspace/../cdktf-toolkit:cached
      - cdktf_node_modules:/workspace/node_modules
    env_file: .env

volumes:
  cdktf_node_modules:
    driver: local
